name: budgetbuddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  feedback: ^3.0.1
  url_launcher: ^6.0.0
  path_provider: ^2.0.2
  image_picker: ^0.8.9

  cupertino_icons: ^1.0.6
  flutter_email_sender: ^6.0.2
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
