// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa2upkNVOhN7AYiG7ZjInjQyX2JM9NGmA',
    appId: '1:176683633038:web:acdab3c73e6a4a7a1cbcdf',
    messagingSenderId: '176683633038',
    projectId: 'budgetbuddy-a07ea',
    authDomain: 'budgetbuddy-a07ea.firebaseapp.com',
    storageBucket: 'budgetbuddy-a07ea.appspot.com',
    measurementId: 'G-0EG9KN5F0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw5lE4LqGIbqgVE4IrTvK80mEJzi18owQ',
    appId: '1:176683633038:android:46ebe351ac7afd0a1cbcdf',
    messagingSenderId: '176683633038',
    projectId: 'budgetbuddy-a07ea',
    storageBucket: 'budgetbuddy-a07ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdl6tk7I9AuukFnOtrwkILcqBGrd1ZGYQ',
    appId: '1:176683633038:ios:1d05d4b040406e601cbcdf',
    messagingSenderId: '176683633038',
    projectId: 'budgetbuddy-a07ea',
    storageBucket: 'budgetbuddy-a07ea.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdl6tk7I9AuukFnOtrwkILcqBGrd1ZGYQ',
    appId: '1:176683633038:ios:1d05d4b040406e601cbcdf',
    messagingSenderId: '176683633038',
    projectId: 'budgetbuddy-a07ea',
    storageBucket: 'budgetbuddy-a07ea.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa2upkNVOhN7AYiG7ZjInjQyX2JM9NGmA',
    appId: '1:176683633038:web:fe2f1a7755d4126e1cbcdf',
    messagingSenderId: '176683633038',
    projectId: 'budgetbuddy-a07ea',
    authDomain: 'budgetbuddy-a07ea.firebaseapp.com',
    storageBucket: 'budgetbuddy-a07ea.appspot.com',
    measurementId: 'G-L16DGN19F8',
  );
}
